name = "my-blog-app"
type = "javascript"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
workers_dev = true
kv_namespaces = [{ binding = "KV", id = "YOUR_KV_NAMESPACE_ID" }]
compatibility_date = "2024-06-01"
